# Generated by Django 3.2.23 on 2024-11-04 18:15

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0051_merge_0049_auto_20240830_1617_0050_auto_20240830_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackerapplication',
            name='fibber',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hackerapplication',
            name='cvs_edition',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hackerapplication',
            name='description',
            field=models.TextField(blank=True, default='.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hackerapplication',
            name='diet',
            field=models.CharField(choices=[('Cap restricció', 'Cap restricció'), ('Vegetarià', 'Vegetarià'), ('Vegà', 'Vegà'), ('Sense gluten', 'Sense gluten'), ('Altres', 'Altres')], default='Cap restricció', max_length=300),
        ),
        migrations.AlterField(
            model_name='hackerapplication',
            name='first_timer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hackerapplication',
            name='gender',
            field=models.CharField(choices=[('NA', 'Prefereixo no contestar'), ('M', 'Home'), ('F', 'Dona'), ('NB', 'No-binari'), ('X', "Prefereixo descriure'm")], default='NA', max_length=23),
        ),
        migrations.AlterField(
            model_name='hackerapplication',
            name='graduation_year',
            field=models.IntegerField(choices=[(2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030')], default=2025),
        ),
        migrations.AlterField(
            model_name='hackerapplication',
            name='lennyface',
            field=models.CharField(blank=True, default=':)', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='hackerapplication',
            name='origin',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='hackerapplication',
            name='tshirt_size',
            field=models.CharField(blank=True, choices=[('XS', 'Unisex - XS'), ('S', 'Unisex - S'), ('M', 'Unisex - M'), ('L', 'Unisex - L'), ('XL', 'Unisex - XL'), ('XXL', 'Unisex - XXL'), ('XXXL', 'Unisex - XXXL')], default='M', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='hackerapplication',
            name='university',
            field=models.CharField(default='Universitat Politècnica de Catalunya - UPC', max_length=300),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='diet',
            field=models.CharField(choices=[('Cap restricció', 'Cap restricció'), ('Vegetarià', 'Vegetarià'), ('Vegà', 'Vegà'), ('Sense gluten', 'Sense gluten'), ('Altres', 'Altres')], default='Cap restricció', max_length=300),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='gender',
            field=models.CharField(choices=[('NA', 'Prefereixo no contestar'), ('M', 'Home'), ('F', 'Dona'), ('NB', 'No-binari'), ('X', "Prefereixo descriure'm")], default='NA', max_length=23),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='graduation_year',
            field=models.IntegerField(choices=[(2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030')], default=2025),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='tshirt_size',
            field=models.CharField(blank=True, choices=[('XS', 'Unisex - XS'), ('S', 'Unisex - S'), ('M', 'Unisex - M'), ('L', 'Unisex - L'), ('XL', 'Unisex - XL'), ('XXL', 'Unisex - XXL'), ('XXXL', 'Unisex - XXXL')], default='M', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='which_hack',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'BitsXLaMarató 2016 Fall'), (1, 'BitsXLaMarató 2016 Winter'), (2, 'BitsXLaMarató 2017 Fall'), (3, 'BitsXLaMarató 2017 Winter'), (4, 'BitsXLaMarató 2018'), (5, 'BitsXLaMarató 2019'), (6, 'BitsXLaMarató 2021'), (7, 'BitsXLaMarató 2022'), (8, 'BitsXLaMarató 2023')], max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='sponsorapplication',
            name='diet',
            field=models.CharField(choices=[('Cap restricció', 'Cap restricció'), ('Vegetarià', 'Vegetarià'), ('Vegà', 'Vegà'), ('Sense gluten', 'Sense gluten'), ('Altres', 'Altres')], default='Cap restricció', max_length=300),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='diet',
            field=models.CharField(choices=[('Cap restricció', 'Sin requerimientos'), ('Vegetarià', 'Vegetariano'), ('Vegà', 'Vegano'), ('Sense gluten', 'Sin gluten'), ('Altres', 'Otros')], default='Cap restricció', max_length=300),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='graduation_year',
            field=models.IntegerField(choices=[(2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030')], default=2025),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='tshirt_size',
            field=models.CharField(blank=True, choices=[('XS', 'Unisex - XS'), ('S', 'Unisex - S'), ('M', 'Unisex - M'), ('L', 'Unisex - L'), ('XL', 'Unisex - XL'), ('XXL', 'Unisex - XXL'), ('XXXL', 'Unisex - XXXL')], default='M', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='which_hack',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'BitsXLaMarató 2016 Fall'), (1, 'BitsXLaMarató 2016 Winter'), (2, 'BitsXLaMarató 2017 Fall'), (3, 'BitsXLaMarató 2017 Winter'), (4, 'BitsXLaMarató 2018'), (5, 'BitsXLaMarató 2019'), (6, 'BitsXLaMarató 2021'), (7, 'BitsXLaMarató 2022'), (8, 'BitsXLaMarató 2023')], max_length=17),
        ),
    ]
