# Generated by Django 3.2.23 on 2024-11-04 19:28

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0051_merge_0049_auto_20240830_1617_0050_auto_20240830_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorapplication',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='mentorapplication',
            name='company',
        ),
        migrations.RemoveField(
            model_name='mentorapplication',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='mentorapplication',
            name='devpost',
        ),
        migrations.RemoveField(
            model_name='mentorapplication',
            name='english_level',
        ),
        migrations.RemoveField(
            model_name='mentorapplication',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='mentorapplication',
            name='first_time_mentor',
        ),
        migrations.RemoveField(
            model_name='mentorapplication',
            name='first_timer',
        ),
        migrations.RemoveField(
            model_name='mentorapplication',
            name='fluent',
        ),
        migrations.RemoveField(
            model_name='mentorapplication',
            name='github',
        ),
        migrations.RemoveField(
            model_name='mentorapplication',
            name='graduation_year',
        ),
        migrations.RemoveField(
            model_name='mentorapplication',
            name='lennyface',
        ),
        migrations.RemoveField(
            model_name='mentorapplication',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='mentorapplication',
            name='online',
        ),
        migrations.RemoveField(
            model_name='mentorapplication',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='mentorapplication',
            name='participated',
        ),
        migrations.RemoveField(
            model_name='mentorapplication',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='mentorapplication',
            name='site',
        ),
        migrations.RemoveField(
            model_name='mentorapplication',
            name='study_work',
        ),
        migrations.RemoveField(
            model_name='mentorapplication',
            name='university',
        ),
        migrations.RemoveField(
            model_name='mentorapplication',
            name='which_hack',
        ),
        migrations.RemoveField(
            model_name='mentorapplication',
            name='why_mentor',
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='type_of_helper',
            field=models.CharField(blank=True, choices=[('Mentor', 'Mentor'), ('Voluntari', 'Voluntari'), ('Metge', 'Metge'), ('Treballadors_FIB', 'Treballadors FIB'), ('Altre', 'Altre')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='which_hack',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'BitsXLaMarató 2016 Fall'), (1, 'BitsXLaMarató 2016 Winter'), (2, 'BitsXLaMarató 2017 Fall'), (3, 'BitsXLaMarató 2017 Winter'), (4, 'BitsXLaMarató 2018'), (5, 'BitsXLaMarató 2019'), (6, 'BitsXLaMarató 2021'), (7, 'BitsXLaMarató 2022'), (8, 'BitsXLaMarató 2023')], max_length=17),
        ),
    ]
