# Generated by Django 3.2.23 on 2024-11-04 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0052_auto_20241104_1815'),
        ('applications', '0052_auto_20241104_1928'),
    ]

    operations = [
    ]
