# Generated by Django 3.2.23 on 2024-11-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0053_merge_0052_auto_20241104_1815_0052_auto_20241104_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorapplication',
            name='graduation_year',
        ),
        migrations.RemoveField(
            model_name='mentorapplication',
            name='which_hack',
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='type_of_helper',
            field=models.CharField(blank=True, choices=[('Mentor', 'Mentor'), ('Voluntari', 'Voluntari'), ('Sanitari', 'Sanitari'), ('Catering', 'Catering'), ('Treballador_FIB', 'Treballador FIB'), ('Altre', 'Altre')], max_length=100, null=True),
        ),
    ]
